sudo: false

os:
  - osx

language: node_js
node_js: lts/*

env:
  matrix:
    - ONLY_RUN_CODE_VERSION=DEV    ONLY_RUN_DART_VERSION=STABLE

addons:
  apt:
    packages:
      - libsecret-1-dev
      - libstdc++6
      - gcc-4.8

services:
  - xvfb

before_install:
  - export ELECTRON_NO_ATTACH_CONSOLE=1

install:
  - npm ci

script:
  - npm test
